### ISSUE TITLE
docker image: compose URL is invalid

### ISSUE THREAD

**Issue by TomasTomecek** [fedora-modularity/base-runtime#1]
```
$ docker build --tag=m8y-plaground:brt -f ./Dockerfile.brt .
Sending build context to Docker daemon 1.038 MB
Step 1/3 : FROM baseruntime/baseruntime
 ---> 5e71af4a5db7
Step 2/3 : COPY files/dnf-copr.repo /etc/yum.repos.d/
 ---> 97bb106082f2
Removing intermediate container 4915cc7e3068
Step 3/3 : RUN microdnf install -y dnf
 ---> Running in d23ec1d75494
Downloading metadata...

(microdnf:1): libdnf-WARNING **: Skipping refresh of buildrepo: cannot update repo 'buildrepo': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors w
ere tried; Last error: Status code: 404 for https://kojipkgs.fedoraproject.org/compose/latest-Fedora-Modular-26/compose/base-runtime/x86_64/os/repodata/repomd.xml
```

**Comment by jankaluza** [comment]
You need to get the base-runtime RPMs from the Server variant. We do not ship any other variant for F26. The `base-runtime` variant which appeared in the compose was there from historic reasons to allow base-runtime team to have stable base-runtime repository while we were playing with the Server variant. I have asked base-runtime team if they are OK with removing it now and they were.

The Server variant is now stable and you should switch to it for building base-runtime container:

https://kojipkgs.fedoraproject.org/compose/latest-Fedora-Modular-26/compose/Server/

The question is how to get only the base-runtime packages out of that flat repo with the DNF you are currently using. I have no answer for that - this flat repo layout has been requested by Modularity and DNF teams for Boltron.

**Comment by jankaluza** [comment]
Note that I can probably submit the PR to add the base-runtime variant back again, but we should have a reason why we are creating "only" base-runtime variant and not variants for other modules. We will surely need a way how to install other modules from the flat repo to Docker container anyway and fixing that just for base-runtime seems wrong to me. Personally I wouldn't like to have this special variant unless it is real blocker.

**Comment by TomasTomecek** [comment]
All I needed was that URL you wrote :) I just want packages. Thank you!

**Comment by contyk** [comment]
If this is about the default yum repo configuration we have in the image, this was fixed in https://github.com/fedora-modularity/baseruntime-docker-tests/commit/e8d1146722e96f19804766231cab793b7583d02f  where we switched to using the Server compose Unfortunately we haven't updated the Docker Hub image since then; our nightly jobs have been failing for a while, for various reasons.

**Comment by TomasTomecek** [comment]
Okay, thanks. Let's leave this open until the fixed version is available on docker hub.

**Comment by contyk** [comment]
It took a few attempts but updated manually.

**Comment by TomasTomecek** [comment]
thank you!
