### ISSUE TITLE
No profile error on dnf module install base-runtime

### ISSUE THREAD

**Issue by alexxa** [fedora-modularity/base-runtime#3]
Me not sure where to report it, if it's a wrong place, please redirect me. 

Using the latest Boltron compose/container, `dnf module install base-runtime` returns: 

```
"Error: No such profile: default. Possible profiles: ['buildroot', 'container', 'srpm-buildroot']"
```

I was told that not every module meant to be installed like `dnf module install <module_name>`, but it's seems to be the profile issue here. Should be there any `default` profile?

**Comment by contyk** [comment]
This is a dnf issue. If the selected profile (`default` in this case) is not available, it should default to an empty list: https://pagure.io/modulemd/blob/master/f/spec.yaml#_68

This module is special. There's no "default" use case for `base-runtime`.

Furthermore, `base-runtime` is pre-installed in your container -- it's what defines it. dnf not registering pre-installed modules is yet another issue it has.

Both of these problems are known and should be documented on the Boltron Known Issues page, unless someone decided not to list them :)

**Comment by alexxa** [comment]
@contyk, thanks.
